name: Docker Build and Push to GHCR

on:
  pull_request:
    branches: [ production, test ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

jobs:
  docker-build-push:
    # Run on PRs to production/test OR manual trigger
    if: contains(fromJson('["production", "test"]'), github.base_ref) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set Docker tag based on target branch
        id: set-tag
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "github.base_ref=${{ github.base_ref }}"
          echo "inputs.branch=${{ inputs.branch }}"

          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET_BRANCH="${{ inputs.branch }}"
          else
            TARGET_BRANCH="${{ github.base_ref }}"
          fi

          echo "TARGET_BRANCH=$TARGET_BRANCH"

          if [[ "$TARGET_BRANCH" == "production" ]]; then
            echo "TAG=latest" >> $GITHUB_OUTPUT
          else
            echo "TAG=test" >> $GITHUB_OUTPUT
          fi


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/ninanor/brownbearpopmodel:${{ steps.set-tag.outputs.TAG }}
